# Non-secret production variables, auto-loaded by Terraform (incl. in CI).
# (The session secret is generated by Terraform; nothing sensitive belongs here.)
aws_region  = "us-east-1"
environment = "prod"

# Custom domain (Route 53 hosted zone in this account). www is added automatically.
domain_name     = "zumbabygrasiele.com"
frontend_origin = "https://zumbabygrasiele.com"

# Emails auto-promoted to admin on register/login. Register with this email in prod to become admin.
admin_bootstrap_emails = ["concordion@mac.com"]
