# Non-secret production variables, auto-loaded by Terraform (incl. in CI).
# (The session secret is generated by Terraform; nothing sensitive belongs here.)
aws_region  = "us-east-1"
environment = "prod"

# Emails auto-promoted to admin on register/login. Register with this email in prod to become admin.
admin_bootstrap_emails = ["concordion@mac.com"]
