# Session HMAC pepper. Generated by Terraform so no human ever handles it. It lives in (encrypted)
# state and in SSM SecureString; it is injected into the Lambda as SESSION_SECRET.

resource "random_password" "session_secret" {
  length  = 48
  special = false
}

resource "aws_ssm_parameter" "session_secret" {
  name        = "/${local.name_prefix}/session-secret"
  description = "HMAC pepper for hashing session tokens."
  type        = "SecureString"
  value       = random_password.session_secret.result
}
